import { readFile, writeFile } from 'node:fs/promises';
import { experimental_generateTypes } from 'wrangler';

const output = 'worker-configuration.d.ts';
const args = process.argv.slice(2);
if (args.some((arg) => arg !== '--check')) {
	throw new Error('Usage: node scripts/worker-types.js [--check]');
}

const generated = await experimental_generateTypes({ config: 'wrangler.jsonc', path: output });
// Wrangler conditionally imports the compiled Worker after a build. That makes
// TypeScript check SvelteKit output and makes generation depend on build order.
// Remove only that import; keep all binding and runtime declarations intact.
// Workaround: https://github.com/cloudflare/workers-sdk/issues/14181
const content = generated.content
	.replace(/\r\n/g, '\n')
	.replace(/[\t ]+$/gm, '')
	.replace(
		/^\s*mainModule: typeof import\("\.\/\.svelte-kit\/cloudflare\/_worker(?:\.js)?"\);\n/m,
		''
	)
	.replace(/\n\tinterface GlobalProps \{\s*\}/, '')
	// The upstream hash includes the removed import. Our check compares all text.
	.replace(
		/^\/\/ Generated by Wrangler by running .*$/m,
		'// Generated by npm run gen using Wrangler; do not edit manually.'
	);

if (args.includes('--check')) {
	const existing = await readFile(output, 'utf8').catch((error) => {
		if (error.code === 'ENOENT') return '';
		throw error;
	});
	if (existing.replace(/\r\n/g, '\n') !== content) {
		console.error(`Types at ${output} are out of date. Run npm run gen.`);
		process.exitCode = 1;
	} else {
		console.log(`Types at ${output} are up to date.`);
	}
} else {
	await writeFile(output, content);
	console.log(`Types written to ${output}.`);
}
